"""
Executor Agent - Validates generated code and prepares it for safe frontend rendering.
Ensures the code is secure, sanitized and ready for client-side execution.
"""
from typing import Dict, Any, Optional
import re
import asyncio

# Import our custom Azure OpenAI wrapper
from app.utils.azure_openai_wrapper import AzureOpenAIWrapper

async def execute_code(code: str, llm: Optional[AzureOpenAIWrapper] = None) -> Dict[str, Any]:
    """
    Validate and prepare the generated code for frontend rendering
    
    Args:
        code: The React component code generated by the coder agent
        llm: Optional LLM for advanced validation (AzureOpenAIWrapper)
        
    Returns:
        Dict containing the sanitized code ready for frontend rendering
    """
    # Simple validation to ensure code looks like a React component
    if not code or not ("import React" in code and "export default" in code):
        # If we have an LLM available, try to fix the code
        if llm:
            try:
                # Let's leave this for now and just return an error
                pass
            except Exception as e:
                print(f"LLM code fixing failed: {str(e)}")
        
        return {
            "valid": False,
            "error": "Generated code does not appear to be a valid React component",
            "component": None
        }
    
    # Basic security checks
    security_issues = []
    
    # Check for potentially dangerous patterns
    danger_patterns = [
        (r"eval\s*\(", "Use of eval() detected"),
        (r"Function\s*\(", "Use of Function constructor detected"),
        (r"document\.write", "Use of document.write detected"),
        (r"innerHTML\s*=", "Direct innerHTML assignment detected"),
        (r"dangerouslySetInnerHTML\s*=\s*\{\s*\{", "Use of dangerouslySetInnerHTML without proper sanitization"),
        (r"localStorage\.", "Direct localStorage access detected"),
        (r"sessionStorage\.", "Direct sessionStorage access detected"),
        (r"window\.open\s*\(", "Window opening detected"),
        (r"fetch\s*\(", "Network requests detected"),
        (r"xhr\.", "XHR requests detected"),
        (r"navigator\.", "Navigator API access detected")
    ]
    
    for pattern, message in danger_patterns:
        if re.search(pattern, code):
            security_issues.append(message)
    
    # Add component type annotation for frontend
    component_name = "UnknownComponent"
    name_match = re.search(r"function\s+([A-Za-z0-9_]+)", code)
    if name_match:
        component_name = name_match.group(1)
    
    # Add special comment for component type
    component_type_comment = f"// @component-type: dynamic"
    code = component_type_comment + "\n" + code
    
    return {
        "valid": len(security_issues) == 0,
        "security_issues": security_issues,
        "component": code,
        "component_name": component_name,
        "warnings": [] if len(security_issues) == 0 else ["Component contains potential security issues"]
    }
